export const dammyShipping = [
  {
    Shipper: 'UPS National',
    Country: 'Germany',
    ShippingCosts: '4,95 €',
    DeliveryTime: '1-3',
  },
  {
    Shipper: 'UPS Express',
    Country: 'Germany',
    ShippingCosts: '17,95 €',
    DeliveryTime: '1',
  },
  {
    Shipper: 'UPS International (EU)',
    Country: 'Belgium',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'France',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Luxembourg',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Monaco',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Netherlands',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Italy',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slovenia',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slow. Rep.',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: 'UPS International (EU)',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'France',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Luxembourg',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Monaco',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Netherlands',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Italy',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slovenia',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slow. Rep.',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: 'UPS International (EU)',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'France',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Luxembourg',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Monaco',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Netherlands',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Italy',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slovenia',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slow. Rep.',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: 'UPS International (EU)',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'France',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Luxembourg',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Monaco',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Netherlands',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Denmark',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Italy',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slovenia',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Slow. Rep.',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: '',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
  {
    Shipper: 'UPS International (EU)',
    Country: 'Austria',
    ShippingCosts: '7,95 €',
    DeliveryTime: '2-4',
  },
];
