import { Button, Typography } from '@material-tailwind/react';
import TemplatePage from './TemplatePage';
import { NavLink } from 'react-router-dom';
import ContribuionsCardWrapper from './ContribuionsCardWrapper';
import ContributionsCard from './ContributionsCard';

const FootherAffiliatePage = () => {
  return (
    <>
      <TemplatePage
        title="AFFILIATE PARTNER-PROGRAM"
        description="
        Become Heimplanet Affiliate Partner"
        img="FootherAffiliatePageImg.webp"
        buttonTitle="Learn More"
        buttonStyle="bg-black text-white"
      />

      <div className="px-[20%] py-[5%]">
        <Typography>
          As an affiliate partner you have the opportunity to promote our
          products and earn commissions. For each sale generated by your link,
          you will receive a commission of 7% and you can move up in the
          commission from a certain number of sales.
        </Typography>
        <Typography className="mt-5 font-bold">
          What our program offers:
        </Typography>
        <ul className="list-disc">
          <li>Start at 7% commission and work your way up to 10%.</li>
          <li>Access to our product data feeds & all links</li>
          <li>
            A cookie lifetime of 14 days - once your link is clicked, you will
            be credited with sales for 2 weeks
          </li>
          <li>
            Regular newsletters with the latest information and promotions
          </li>
        </ul>
        <div className="flex mt-10">
          <Typography className="font-bold">
            Join now for free and become a partner:
          </Typography>
          <Typography className="ml-2">Join now</Typography>
        </div>
      </div>

      <div className="bg-[#f6f6f6] px-[10%] py-[5%]">
        <div className="flex justify-between w-full items-center ">
          <Typography className="sm:text-4xl text-2xl ">
            MORE CONTRIBUTIONS
          </Typography>
          <NavLink to="/blogs/collabs/maharishi-x-heimplanet-the-cave">
            <Button
              color="white"
              size="lg"
              className="rounded-none border-[1px] border-black hover:bg-black hover:text-white"
            >
              READ MORE
            </Button>
          </NavLink>
        </div>
        <ContribuionsCardWrapper>
          <ContributionsCard
            title="SUP ADVENTURES - DOORSTEP TO OCEAN IN ONE DAY"
            description="It was a sunny day when we decided to explore the pristine nature right outside our doorstep."
            img="contributions-1.webp"
          />
          <ContributionsCard
            title="OUR TIPS FOR TRAVELING LIGHT"
            description="Space-saving and lightweight packing is a fundamental skill for any globetrotter."
            img="contributions-3.jpg"
          />
          <ContributionsCard
            title="CAMPING IN GERMANY"
            description="More openings are in sight and it's time to plan the first trips outdoors. If you want to spend a night at a campsite in beautiful surroundings in Germany without being woken up by slamming car doors or motorhome generators, only to find that the first thing you see is a wall of caravans, it's not so easy."
            img="contributions-2.webp"
          />
        </ContribuionsCardWrapper>
      </div>
    </>
  );
};

export default FootherAffiliatePage;
